### ISSUE TITLE
Plugin not work with specific roles

### ISSUE THREAD

**Issue by solucionesuno** [stuartduff/WooCommerce-Dynamic-Pricing-Table#15]
it show all disscount toghere, and not filter by user role.

**Comment by delacruzdesign** [comment]
Me pasa exactamente igual. ¿Has conseguido solucionarlo?

**Comment by solucionesuno** [comment]
@delacruzdesign  Si, al final me hice un plugin propio para solucionarlo. escribirme a luis@iontics.com coméntame que necesitas a ver si te puedo ayudar.

**Comment by stuartduff** [comment]
I'm closing out this issue as it's a duplicate of issue #10
