### ISSUE TITLE
Bulk pricing not displaying decimals

### ISSUE THREAD

**Issue by pakoman07** [stuartduff/WooCommerce-Dynamic-Pricing-Table#3]
How can I make the table to display "pricing per item" with decimals?

**Comment by SturmB** [comment]
I forked the repo and made a few slight changes so that the prices display as decimals now, at least for a Bulk Pricing table using either the Price Discount model or Fixed Price model.

https://github.com/SturmB/woocommerce-dynamic-pricing-table

**Comment by pakoman07** [comment]
Awesome! It works like a charm. Thanks.

**Comment by stuartduff** [comment]
@pakoman07 @SturmB I have added a fix for this to the main plugin and cheers for pointing this out ;)
