### ISSUE TITLE
Product list not displaying

### ISSUE THREAD

**Issue by CameronGilroy** [stuartduff/WooCommerce-Dynamic-Pricing-Table#7]
When the plugin is activated the products list in the admin (/wp-admin/edit.php?post_type=product) is all blank.

Below is the error message.

`2016/09/03 07:40:45 [error] 30751#30751: *2792 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function wc_add_notice() in /var/www/html/wp-content/plugins/woocommerce-dynamic-pricing-table-master/woocommerce-dynamic-pricing-table.php:353
Stack trace:
#0 /var/www/html/wp-content/plugins/woocommerce-dynamic-pricing-table-master/woocommerce-dynamic-pricing-table.php(363): WC_Dynamic_Pricing_Table->role_discount_notification_message()
#1 /var/www/html/wp-includes/plugin.php(600): WC_Dynamic_Pricing_Table->output_dynamic_pricing_role_message(Object(WP))
#2 /var/www/html/wp-includes/class-wp.php(738): do_action_ref_array('wp', Array)
#3 /var/www/html/wp-includes/functions.php(963): WP->main(Array)
#4 /var/www/html/wp-admin/includes/post.php(1070): wp(Array)
#5 /var/www/html/wp-admin/includes/class-wp-posts-list-table.php(142): wp_edit_posts_query()
#6 /var/www/html/wp-admin/edit.php(176): WP_Posts_List_Table->prepare_items()
#7 {main}

  thrown in /var/www/html/wp-content/plugins/woocommerce-dynamic-pricing-table-master/woocommerce-dynamic-" while reading response header from upstream, client: 58.179.25.195, server: _, request: "GET /wp-admin/edit.php?post_type=product HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "45.63.24.64", referrer: "https://45.63.24.64/wp-admin/plugins.php?plugin_status=all&paged=1&s"
2016/09/03 07:42:31 [error] 30751#30751: *2792 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function wc_add_notice() in /var/www/html/wp-content/plugins/woocommerce-dynamic-pricing-table-master/woocommerce-dynamic-pricing-table.php:353`

**Comment by CameronGilroy** [comment]
the page /wp-admin/edit.php?post_type=product is only blank, below are the error messages.

`2016/09/03 07:40:45 [error] 30751#30751: *2792 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function wc_add_notice() in /var/www/html/wp-content/plugins/woocommerce-dynamic-pricing-table-master/woocommerce-dynamic-pricing-table.php:353
Stack trace:
#0 /var/www/html/wp-content/plugins/woocommerce-dynamic-pricing-table-master/woocommerce-dynamic-pricing-table.php(363): WC_Dynamic_Pricing_Table->role_discount_notification_message()
#1 /var/www/html/wp-includes/plugin.php(600): WC_Dynamic_Pricing_Table->output_dynamic_pricing_role_message(Object(WP))
#2 /var/www/html/wp-includes/class-wp.php(738): do_action_ref_array('wp', Array)
#3 /var/www/html/wp-includes/functions.php(963): WP->main(Array)
#4 /var/www/html/wp-admin/includes/post.php(1070): wp(Array)
#5 /var/www/html/wp-admin/includes/class-wp-posts-list-table.php(142): wp_edit_posts_query()
#6 /var/www/html/wp-admin/edit.php(176): WP_Posts_List_Table->prepare_items()
#7 {main}
  thrown in /var/www/html/wp-content/plugins/woocommerce-dynamic-pricing-table-master/woocommerce-dynamic-" while reading response header from upstream, client: 58.179.25.195, server: _, request: "GET /wp-admin/edit.php?post_type=product HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "45.63.24.64", referrer: "https://45.63.24.64/wp-admin/plugins.php?plugin_status=all&paged=1&s"
2016/09/03 07:42:31 [error] 30751#30751: *2792 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function wc_add_notice() in /var/www/html/wp-content/plugins/woocommerce-dynamic-pricing-table-master/woocommerce-dynamic-pricing-table.php:353`

**Comment by stuartduff** [comment]
Thanks @CameronGilroy I just added a fix for this in v1.0.5 https://github.com/stuartduff/woocommerce-dynamic-pricing-table/releases/tag/1.0.5
